#!/usr/bin/env python

import requests
import sys
import json

obj = sys.stdin
data = json.loads(obj.read())

uri = data.get("source").get("uri")
r = requests.get(uri)

version = r.text
 
out = list()
out.append({"release": version})

print(json.dumps(out))